
[General]
	#Allow to recycle magic items by consuming books [false/true|default:true]
	recycle_magic_item = true
	#Time to recycle an item [5..10000|default:100]
	#Range: 5 ~ 10000
	time_to_recycle = 100
	#Automation stops after a delay without processing [false/true|default:true]
	permanent_automation = true
	#Allow recycler sounds [false/true|default:true]
	allow_sound = true
	#Chance of losing 50% when recycling [0..100|default:0]
	#Range: 0 ~ 100
	chance_loss = 0
	#Only use your custom recycling recipes (from the file 'user_defined_recipes' in the config folder) [false/true|default:false]
	only_user_recipes = false
	#Allow to separate the enchantments of Enchanted Book by consuming books [false/true|default:true]
	recycle_enchanted_book = true

